[global]
dataFrameSerialization = "legacy"

[server]
maxUploadSize = 10
runOnSave = true

[runner]
magicEnabled = true
fastReruns = false

[mapbox]

[theme]
base="light"
primaryColor="#226216"
backgroundColor="#f5fcff"
secondaryBackgroundColor="#e5ecef"
textColor="#000000"
font="sans serif"